@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/?limit=10&page=4
### Detalha um recado específico
GET {{baseUrl}}/recados/2
### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Novo recado criado via API",
    "de": "Joana",
    "para": "João"
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Atualiza Recado",
    "de": "Joana",
    "para": "João",
    "lido": true
  }

### Remove/Exclui um recado existente
DELETE {{baseUrl}}/recados/2


